#ifndef _ACTION_ID_H
#define _ACTION_ID_H

#define   Bow                      1
#define   fst_F_R_S                3
#define   fst_F_L_S                4
#define   fst_F_R_L_M              5
#define   fst_F_L_R_M              6
#define   fst_F_R_E                7
#define   fst_F_L_E                8
#define   fst_FRT_R_M              9
#define   fst_FLT_L_M              10
#define   fst_B_R_S                11
#define   fst_B_L_S                12
#define   fst_B_R_M                13
#define   fst_B_L_M                14
#define   fst_B_R_E                15
#define   fst_B_L_E                16
#define   fst_RFT                  17
#define   fst_LFT                  18
#define   fst_RBT                  19
#define   fst_LBT                  20
#define   Fst_R                    21
#define   Fst_L                    22
#define   fst_RT                   23
#define   fst_LT                   24
#define   Sit_down                 25
#define   Stand_up                 26
#define   F_getup                  27
#define   B_getup                  28
#define   Fst_Ready                30
#define   Walk_Ready               31
#define   F_S_L                    32
#define   F_S_R                    34
#define   F_M_L                    36
#define   F_M_R                    38
#define   F_E_L                    40
#define   F_E_R                    42
#define   B_S_L                    44
#define   B_S_R                    46
#define   B_M_L                    48
#define   B_M_R                    50
#define   B_E_L                    52
#define   B_E_R                    54
#define   LT_S_L                   56
#define   LT_S_R                   58
#define   LT_M_L                   60
#define   LT_M_R                   62
#define   LT_E_L                   64
#define   LT_E_R                   66
#define   RT_S_L                   68
#define   RT_S_R                   70
#define   RT_M_L                   72
#define   RT_M_R                   74
#define   RT_E_L                   76
#define   RT_E_R                   78
#define   L_S_L                    80
#define   L_S_R                    82
#define   L_M_L                    84
#define   L_M_R                    86
#define   L_E_L                    88
#define   L_E_R                    90
#define   R_S_L                    92
#define   R_S_R                    94
#define   R_M_L                    96
#define   R_M_R                    98
#define   R_E_L                    100
#define   R_E_R                    102
#define   FLT_S_L                  104
#define   FLT_S_R                  106
#define   FLT_M_L                  108
#define   FLT_M_R                  110
#define   FLT_E_L                  112
#define   FLT_E_R                  114
#define   FRT_S_L                  116
#define   FRT_S_R                  118
#define   FRT_M_L                  120
#define   FRT_M_R                  122
#define   FRT_E_L                  124
#define   FRT_E_R                  126
#define   BLT_S_L                  128
#define   BLT_S_R                  130
#define   BLT_M_L                  132
#define   BLT_M_R                  134
#define   BLT_E_L                  136
#define   BLT_E_R                  138
#define   BRT_S_L                  140
#define   BRT_S_R                  142
#define   BRT_M_L                  144
#define   BRT_M_R                  146
#define   BRT_E_L                  148
#define   BRT_E_R                  150
#define   LTA_S_L                  152
#define   LTA_S_R                  154
#define   LTA_M_L                  156
#define   LTA_M_R                  158
#define   LTA_E_L                  160
#define   LTA_E_R                  162
#define   RTA_S_L                  164
#define   RTA_S_R                  166
#define   RTA_M_L                  168
#define   RTA_M_R                  170
#define   RTA_E_L                  172
#define   RTA_E_R                  174
#define   FL_S_L                   176
#define   FL_S_R                   178
#define   FL_M_L                   180
#define   FL_M_R                   182
#define   FL_E_L                   184
#define   FL_E_R                   186
#define   FR_S_L                   188
#define   FR_S_R                   190
#define   FR_M_L                   192
#define   FR_M_R                   194
#define   FR_E_L                   196
#define   FR_E_R                   198
#define   BL_S_L                   200
#define   BL_S_R                   202
#define   BL_M_L                   204
#define   BL_M_R                   206
#define   BL_E_L                   208
#define   BL_E_R                   210
#define   BR_S_L                   212
#define   BR_S_R                   214
#define   BR_M_L                   216
#define   BR_M_R                   218
#define   BR_E_L                   220
#define   BR_E_R                   222
#define   stairs_up1               224
#define   stairs_up2               225
#define   stairs_up3               226
#define   Init                     227
#define   stairs_down1             228
#define   stairs_down2             229
#define   stairs_down3             230
#define   F_Throw1                 231
#define   F_Throw2                 232
#define   A_Moving_R               233
#define   A_Moving_L               234
#define   A_F_attack               235
#define   P_R_A                    236
#define   P_L_A                    237
#define   FR_attack                238
#define   FL_attack                239



#endif
